# Replace the baseurl with the name of this repository.
baseurl: "/aplicaciones/appsistac/ods"
#url: ""
# Replace "open-sdg" with the name of your GitHub organization, and
# "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "./opensdg-datos"

# Replace this value as needed.
org_name: istac

# International Support
country:
  name: Canarias
  adjective: Canario

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: menu.inicio
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /faq
    translation_key: menu.faq
  - path: /guidance
    translation_key: menu.guidance

defaults:
  - scope:
      path: ""
    values:
      language: "es"
      header_image: "header.png"
      header_text_image: "header_text_image.png"
      texto_serie_ocecas: "Indicador calculado utilizando una metodología armonizada entre los órganos centrales de estadística de las comunidades autónomas"
      imagen_serie_ocecas: "ocecas_metadata_image.jpg"
      texto_serie: ""
      imagen_serie : "metadata_image.jpg"
      nuts_local: "ES70"

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: "https://www3.gobiernodecanarias.org/aplicaciones/appsistac/ods/assets/img/ods_images"

map_lat: 28.2890655
map_lon: -16.0290619
map_zoom: 7

# Lista CSV sin espacios de códigos de CL_AREA_ES53
# https://www3.gobiernodecanarias.net/aplicaciones/structural-resources-internal-istac/#structuralResources/codelists/codelist;id=ISTAC%3ACL_AREA_ES(03.000)
orden_territorio: "ES,ES70"

documento_metodologia: "IDS_Canarias_Metodologia_V1.1.pdf"
