# Jekyll configuration for Open SDG platform
#
# You will need to change all of the capitalized variables below according
# to your Github setup. For example, if your site and data repositories are:
# -- https://github.com/my-awesome-github-org/my-awesome-site-repo
# -- https://github.com/my-awesome-github-org/my-awesome-data-repo
# Then you would want to make these replacements throughout this file:
# -- replace "my-github-org" with "my-awesome-github-org"
# -- replace "open-sdg-site-starter" with "my-awesome-site-repo"
# -- replace "open-sdg-data-starter" with "my-awesome-data-repo"

remote_theme: open-sdg/open-sdg@1.1.0

# Replace this title as needed.
title: Indicadores para los Objetivos de Desarrollo Sostenible
# Replace the baseurl with the name of this repository.
baseurl: ""
#url: ""
data_dir: _data
environment: production
# Replace "open-sdg" with the name of your GitHub organization, and
# "open-sdg-data-starter" with the name of your data repository.

remote_data_prefix: "http://localhost:5000"
# remote_data_prefix: "./opensdg-datos"

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target
create_pages: true

analytics:
  ga_prod: ""

# Social media accounts.
twitter: "MyTwitterAccount"

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com

# Github Repo for Data
# Replace this value as needed.
repo_name: edatos-opensdg-web
branch: develop
# Replace this value as needed.
org_name: istac

# Build settings
markdown: kramdown

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Canarias
  adjective: Canario

# Optionally uncomment and update the settings below to control the frontpage heading and instructions.
#frontpage_heading: Australian data for Sustainable Development Goal indicators
#frontpage_instructions: ""

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: menu.inicio
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /faq
    translation_key: menu.faq
  - path: /guidance
    translation_key: menu.guidance


# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
  - es

# Color set to be used for graphs, see file https://github.com/open-sdg/open-sdg/blob/1.1.0-dev/_includes/assets/js/chartColors.js
# (lines 24-25). Available presets are 'default' (used when this config is not set); 'sdg', which has a lot more colors;
# and 'custom', which requires a list of colors to be set on the property 'graph_color_list' and can be limited with
# the property 'graph_color_number'.
graph_color_set: custom
graph_color_number: 6
graph_color_list:
  - "AA6544"
  - "B55380"
  - "657893"
  - "E52727"
  - "7B6079"
  - "3A6351"
  - "3EA679"
  - "85603F"
  - "AD932A"
  - "DD69CC"
  - "BF4C4B"
  - "5D5D5D"
  - "09A5A9"

# This makes sure that all pages have a language.
defaults:
  - scope:
      path: ""
    values:
      language: "es"
      header_image: "header.png"
      header_text_image: "header_text_image.png"
      texto_serie_ocecas: "Indicador calculado utilizando una metodología armonizada entre los órganos centrales de estadística de las comunidades autónomas"
      imagen_serie_ocecas: "ocecas_metadata_image.jpg"
      texto_serie: ""
      imagen_serie : "metadata_image.jpg"

# Ejemplo de map_options
# map_options:
#   # If you would like to use tile (background) imagery, use these:
#   tileURL: https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token={accessToken}
#   tileOptions:
#     id: mapbox/streets-v11
#     accessToken: pk.eyJ1IjoianJvZGNvciIsImEiOiJja240bjEwdjMwa3EwMnZvMDdjejF6MXQ3In0.rwgQT9lyjU77AT7fSJD2vw
#     attribution: Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>

# Ejemplo de map_layer
# map_layers:
#  - geojson_file: https://datos.canarias.es/catalogos/estadisticas/dataset/6dd8baf4-14f4-43a3-88b2-984d034c965c/resource/d31b5422-df3b-4eae-b0eb-b4acbecb8ef0/download/municipios_20170101_generalizado.json
#    name_property: etiqueta
#    id_property: geocode
#    output_subfolder: regions
#    filename_prefix: indicator_
   


# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://estadisticas.arte-consultores.com/aplicaciones/appsistac/ods/assets/img/ods_images

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins

exclude:
  - vendor
  - scripts
  - remotedata
  - Gemfile
  - Gemfile.lock
  - README
  - README.md
  - LICENSE
