# Replace this title as needed.
title: Indicadores para los Objetivos de Desarrollo Sostenible BALEARES
# Replace the baseurl with the name of this repository.
baseurl: "/aplicaciones/appsistac/ods" # TODO: Esto probablemente haya que cambiarlo
#url: ""
# Replace "open-sdg" with the name of your GitHub organization, and
# "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "./opensdg-datos"

# Replace this value as needed.
org_name: ibestat

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Baleares
  adjective: Balear

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: menu.inicio
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /faq
    translation_key: menu.faq
  - path: /guidance
    translation_key: menu.guidance

goal_image_base: "https://ibestat.edatos.io/aplicaciones/appsistac/ods/assets/img/ods_images"

# The list of languages that are translated. The first one is the default.
languages:
  - es
  - ca