# Replace the baseurl with the name of this repository.
baseurl: "/aplicaciones/appsistac/ods"
#url: ""
# Replace "open-sdg" with the name of your GitHub organization, and
# "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "./opensdg-datos"

# Replace this value as needed.
org_name: istac

# International Support
country:
  name: Canarias
  adjective: Canario

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: menu.inicio
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /faq
    translation_key: menu.faq
  - path: /guidance
    translation_key: menu.guidance

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: "https://www3.gobiernodecanarias.org/aplicaciones/appsistac/ods/assets/img/ods_images"