# Replace this title as needed.
title: Indicadores para los Objetivos de Desarrollo Sostenible
# Replace the baseurl with the name of this repository.
baseurl: "/ods"
#url: ""
# Replace "open-sdg" with the name of your GitHub organization, and
# "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "./opensdg-datos"

# Replace this value as needed.
org_name: ibestat

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Illes Balears
  adjective: Balear

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /
    translation_key: menu.inicio
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /faq
    translation_key: menu.faq
  - path: /guidance
    translation_key: menu.guidance

defaults:
  - scope:
      path: ""
    values:
      language: "es"
      header_image: "header.png"
      header_text_image: "header_text_image.png"
      texto_serie_ocecas: "Indicador calculado utilizando una metodología armonizada entre los órganos centrales de estadística de las comunidades autónomas"
      imagen_serie_ocecas: "ocecas_metadata_image.jpg"
      texto_serie: ""
      imagen_serie : "metadata_image.jpg"
      nuts_local: "ES53"

# Ejemplo de map_options
map_options:
  # If you would like to use tile (background) imagery, use these:
  tileURL: http://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token={accessToken}
  tileOptions:
    id: mapbox/streets-v11
    accessToken: pk.eyJ1IjoianJvZGNvciIsImEiOiJja240bjEwdjMwa3EwMnZvMDdjejF6MXQ3In0.rwgQT9lyjU77AT7fSJD2vw
    attribution: <p>Attribution Example</p>

map_layers:
 - geojson_file: maps/islasBaleares.json
   name_property: NOM
   id_property: CODNUT3
   output_subfolder: regions
   filename_prefix: indicator_

goal_image_base: "https://ibestat.edatos.io/ods/assets/img/ods_images"

# The list of languages that are translated. The first one is the default.
languages:
  - es
  - ca